# This file is a template, and might need editing before it works on your project.
# Official docker image.
image: docker:latest

# When using dind, it's wise to use the overlayfs driver for
# improved performance.
variables:
  DOCKER_DRIVER: overlay2
  CONTAINER_IMAGE_RELEASE: registry.gitlab.com/$CI_PROJECT_PATH
  CONTAINER_IMAGE_TEST: registry.gitlab.com/$CI_PROJECT_PATH__TEST

services:
  - docker:dind

before_script:
   - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
#  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

build:
  stage: build
  script:
    - docker pull $CONTAINER_IMAGE_TEST:latest || true
    - docker build --cache-from $CONTAINER_IMAGE:latest --tag $CONTAINER_IMAGE_TEST:$CI_BUILD_REF --tag $CONTAINER_IMAGE_TEST:latest .
    - docker push $CONTAINER_IMAGE_TEST:$CI_BUILD_REF
    - docker push $CONTAINER_IMAGE_TEST:latest

test1:
  stage: test
  script:
    - docker pull $CONTAINER_IMAGE_TEST
    - docker run $CONTAINER_IMAGE_TEST /bin/sh test.sh
    
# test2:
#   stage: test
#   script:
#     - docker pull $CONTAINER_IMAGE_TEST
#     - docker run $CONTAINER_IMAGE_TEST /bin/sh test2.sh
    
release-image:
  stage: release
  script:
    - docker pull $CONTAINER_IMAGE_TEST
    - docker tag $CONTAINER_IMAGE_TEST $CONTAINER_IMAGE_RELEASE
    - docker push $CONTAINER_IMAGE_RELEASE
  only:
    - master
