env:
  IMAGE_NAME: 'pyhello'

steps:
  - label: 'Build docker image'
    command: 'docker build -t ${IMAGE_NAME} .'
    plugins:
      docker-compose#v1.8.0:
        run: agent

  - wait

  - label: ':hammer: Tests'
    command: 'docker run ${IMAGE_NAME}:latest /bin/sh test.sh'
    plugins:
      docker-compose#v1.8.0:
        run: agent
