env:
  IMAGE_NAME: 'pyhello'


steps:
  - label: 'Build docker image'
    command: 'docker build -t ${IMAGE_NAME} .'

  - wait

  - label: ':hammer: Tests'
    command: 'docker run ${IMAGE_NAME}:latest /bin/sh test.sh'
